#!/bin/bash
#
# rr can be used in place of rm on a Mac to remove a file or directory.
# Instead of deleting it, it just moves it to the Trash.
# This is nice for huge directory trees because it happens instantly.
#
# Options:
#   -f   When deleting a directory, force deletion of the existing
#        ~/.Trash/{dirname} if there is already one in the trash.

force=false
if [ "$1" == "-f" ]
then
  force=true
  shift
fi

for filename
do
  if [ -f "$filename" -o -d "$filename" ]
  then
    if $force
    then
      rm -rf "~/.Trash/$filename"
    fi
    mv "$filename" ~/.Trash/
  fi
done
